---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ileys/public_html/
    # - /bin/cp -R /home/ileys/repositories/ileys-website2/public/index.html  $DEPLOYPATH
    # - /bin/cp -R /home/ileys/repositories/ileys-website2/public/asset  $DEPLOYPATH
    # - /bin/cp -R /home/ileys/repositories/ileys-website2/public/detergent  $DEPLOYPATH
    # - /bin/cp -R /home/ileys/repositories/ileys-website2/public/enterprise  $DEPLOYPATH
      - /bin/cp -R /home/ileys/repositories/ileys-website2/dist $DEPLOYPATH
