---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ileys/public_html/
    - /bin/cp -R /home/ileys/repositories/ileys-website2/asset/*  $DEPLOYPATH
    - /bin/cp -R /home/ileys/repositories/ileys-website2/css/*  $DEPLOYPATH
    - /bin/cp -R /home/ileys/repositories/ileys-website2/detergent/*  $DEPLOYPATH
    - /bin/cp -R /home/ileys/repositories/ileys-website2/enterprise/*  $DEPLOYPATH 
    - /bin/cp -R /home/ileys/repositories/ileys-website2/index.html  $DEPLOYPATH 